import { Mulish } from 'next/font/google'
import "./globals.css";
import { RiTwitterXLine } from "react-icons/ri";
import { IoMdMail } from "react-icons/io";
import "./globals.css";


import { FaFacebook, FaLinkedin, FaMailBulk } from "react-icons/fa";
import { FaTwitter } from "react-icons/fa";
import Link from "next/link";
import ButtonAll from '@/components/ButtonAll';

const mulish = Mulish({

     subsets: ['latin'],
})


export const metadata = {
     title: "Website",
     description: "Generated by create next app",
};

export default function RootLayout({ children }) {

     const navOptions = <>

          <li className="text-md font-bold m-4 hover:text-[#121643] transition-all cursor-pointer hover:bg-transparent"><Link href="/">Home</Link></li>
          <li className="text-md font-bold m-4 hover:text-[#121643] transition-all cursor-pointer hover:bg-transparent"><Link href="/about">About</Link></li>
          <li className="text-md font-bold m-4 hover:text-[#121643] transition-all cursor-pointer hover:bg-transparent"><Link href="/pricing">Pricing</Link></li>
          <li className="text-md font-bold m-4 hover:text-[#121643] transition-all cursor-pointer hover:bg-transparent"><Link href="/blog">Blog</Link></li>
          <li className="text-md font-bold m-4 hover:text-[#121643] transition-all cursor-pointer hover:bg-transparent"><Link href="/tryDemo">Try Demo</Link></li>
          <li className="text-md font-bold m-4 hover:text-[#121643] transition-all cursor-pointer hover:bg-transparent"> <Link href="/">Contact</Link></li>



     </>

     return (
          <html lang="en">
               <body className={mulish.className}>


                    <div className="navbar container lg:max-w-7xl mx-auto pt-3 py-6">
                         <div className="navbar-start">
                              <div className="dropdown">
                                   <div tabIndex={0} role="button" className="btn btn-ghost lg:hidden">
                                        <svg
                                             xmlns="http://www.w3.org/2000/svg"
                                             className="h-5 w-5"
                                             fill="none"
                                             viewBox="0 0 24 24"
                                             stroke="currentColor">
                                             <path
                                                  strokeLinecap="round"
                                                  strokeLinejoin="round"
                                                  strokeWidth="2"
                                                  d="M4 6h16M4 12h8m-8 6h16" />
                                        </svg>
                                   </div>
                                   <ul
                                        tabIndex={0}
                                        className="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
                                        {navOptions}
                                   </ul>
                              </div>
                              <a className="btn btn-ghost text-xl">LOGO</a>
                         </div>
                         <div className="navbar-center rounded-none  hidden lg:flex">
                              <ul className="menu menu-horizontal px-1 ">
                                   {navOptions}
                              </ul>
                         </div>
                         <div className="navbar-end">
                              <ButtonAll content="Sign Up"></ButtonAll>
                         </div>
                    </div>





                    <main className="">
                         {children}
                    </main>


                    <footer className="footer px-10 lg:px-48 flex-none lg:flex items-end justify-between mt-40 bg-[#030712] text-neutral-content p-10">
                         <aside>

                              <p className='text-xl flex gap-3 items-center'>
                                   <IoMdMail />  info@ai-assist.com
                              </p>
                              <nav className='mt-4'>
                                   <h6 className="footer-title">Social</h6>
                                   <div className="grid grid-flow-col gap-4">
                                        <a className='text-2xl' href=""><FaFacebook /></a>
                                        <a className='text-2xl' href=""><RiTwitterXLine /></a>
                                        <a className='text-2xl' href=""><FaLinkedin></FaLinkedin></a>
                                   </div>
                              </nav>
                         </aside>

                         <p className='text-white'>© {new Date().getFullYear()}  AI-Assist. All rights reserved. | Privacy Policy | Terms of Service</p>
                    </footer>

               </body>
          </html >
     );
}



{/* <div className="flex -mx-2 space-x-5">

</div> */}
