import { Mulish } from 'next/font/google'
import "./globals.css";
import { RiTwitterXLine } from "react-icons/ri";
import { IoMdMail } from "react-icons/io";
import "./globals.css";


import { FaFacebook, FaLinkedin, FaMailBulk } from "react-icons/fa";
import { FaTwitter } from "react-icons/fa";
import Link from "next/link";
import ButtonAll from '@/components/ButtonAll';
import Navbar from '@/components/Navbar.js';

const mulish = Mulish({

     subsets: ['latin'],
})


export const metadata = {
     title: "Website",
     description: "Generated by create next app",
};

export default function RootLayout({ children }) {



     return (
          <html lang="en">
               <body className={mulish.className}>


              <div className='px-2 mx-auto lg:max-w-7xl'>
              <Navbar></Navbar>
              </div>





                    <main className="px-2 lg:max-w-7xl mx-auto">
                         {children}
                    </main>


                    <footer className="footer px-10 lg:px-48 flex-none lg:flex items-end justify-between mt-40 bg-[#030712] text-neutral-content p-10">
                         <aside>

                              <p className='text-xl flex gap-3 items-center'>
                                   <IoMdMail />  info@ai-assist.com
                              </p>
                              <nav className='mt-4'>
                                   <h6 className="footer-title">Social</h6>
                                   <div className="grid grid-flow-col gap-4">
                                        <a className='text-2xl' href=""><FaFacebook /></a>
                                        <a className='text-2xl' href=""><RiTwitterXLine /></a>
                                        <a className='text-2xl' href=""><FaLinkedin></FaLinkedin></a>
                                   </div>
                              </nav>
                         </aside>

                         <p className='text-white'>© {new Date().getFullYear()}  AI-Assist. All rights reserved. | Privacy Policy | Terms of Service</p>
                    </footer>

               </body>
          </html >
     );
}



{/* <div className="flex -mx-2 space-x-5">

</div> */}
